/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class avalco_network_vpn_base_VirtualInternetFace_ReceiveListener */

#ifndef _Included_avalco_network_vpn_base_VirtualInternetFace_ReceiveListener
#define _Included_avalco_network_vpn_base_VirtualInternetFace_ReceiveListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
